### ISSUE TITLE
These entities are still listed as having name errors after full update of OctoPi/Plugins.

### ISSUE THREAD

**Issue by nerlins** [cmroche/OctoPrint-HomeAssistant#115] opened 2023-08-18 11:52 UTC
List of affected entities:

switch.octocr10_emergency_stop
switch.octosv01_shutdown_system
switch.octocr10_cancel_print
switch.octocr10_shutdown_system
switch.octosv01_emergency_stop
switch.octosv01_cancel_print

These are two systems with the same entities listing as having the name issue.

**Comment by nerlins** [comment] 2023-08-18 12:09
Well. I might need to look at the troubleshooting over at this issue:

https://github.com/cmroche/OctoPrint-HomeAssistant/issues/114

**Comment by jneilliii** [comment] 2023-08-18 14:57
yeah, this appears to be duplicate of comment https://github.com/cmroche/OctoPrint-HomeAssistant/issues/114#issuecomment-1673593093, which they were able to fix by getting rid of retained messages.

**Comment by nerlins** [comment] 2023-08-25 12:18
I used the instructions from the other post and got the errors cleared out.

**Closed as completed** 2023-08-25 12:17 UTC
